# Data Understanding
In this section we will explore and analize the dataset, detect missing values and identify patterns that will guide the data preparation and modeling steps.

## Imports

In [1]:
import pandas as pd

## Import the dataset

In [10]:
ds = pd.read_csv("data/escs_trend.csv")
ds.head()

,cycnt,cycle,cnt,schoolid,studentid,oecd,escs_trend,hisei_trend,homepos_trend,paredint_trend
0,05ARE,5,ARE,1,1,0,0.3226,82.410004,-0.351700,16.0
1,05ARE,5,ARE,1,2,0,0.0598,NaN,0.010140,16.0
2,05ARE,5,ARE,1,3,0,-0.8984,51.500000,-0.302142,12.0
3,05ARE,5,ARE,1,4,0,0.4869,81.400002,0.725674,12.0
4,05ARE,5,ARE,1,5,0,-0.5238,63.029999,-0.105597,12.0

In [ ]:
print("Dataset shape:", ds.shape)
ds.info()

Dataset shape: (1447787, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1447787 entries, 0 to 1447786
Data columns (total 10 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   cycnt           1447787 non-null  object
 1   cycle           1447787 non-null  int64
 2   cnt             1447787 non-null  object
 3   schoolid        1447787 non-null  int64
 4   studentid       1447787 non-null  int64
 5   oecd            1447787 non-null  int64
 6   escs_trend      1413056 non-null  float64
 7   hisei_trend     1351262 non-null  float64
 8   homepos_trend   1419125 non-null  float64
 9   paredint_trend  1392706 non-null  float64
dtypes: float64(4), int64(4), object(2)
memory usage: 110.5+ MB

In [ ]:
ds.describe()

,cycle,schoolid,studentid,oecd,escs_trend,hisei_trend,homepos_trend,paredint_trend
count,1.447787e+06,1.447787e+06,1.447787e+06,1.447787e+06,1.413056e+06,1.351262e+06,1.419125e+06,1.392706e+06
mean,6.070506e+00,5.530517e+02,6.736302e+03,6.062922e-01,-4.070169e-01,4.937063e+01,1.136132e-01,1.319475e+01
std,8.317076e-01,4.152367e+03,7.811206e+03,4.885715e-01,1.141891e+00,2.261602e+01,5.991336e-01,3.041958e+00
min,5.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-9.861800e+00,1.101000e+01,-6.801333e+00,3.000000e+00
25%,5.000000e+00,6.400000e+01,2.161000e+03,0.000000e+00,-1.143700e+00,2.848000e+01,-2.456261e-01,1.200000e+01
50%,6.000000e+00,1.370000e+02,4.335000e+03,1.000000e+00,-3.205000e-01,5.037000e+01,1.489440e-01,1.450000e+01
75%,7.000000e+00,2.480000e+02,7.627000e+03,1.000000e+00,4.896000e-01,7.050000e+01,4.976700e-01,1.600000e+01
max,7.000000e+00,5.011900e+04,5.479700e+04,1.000000e+00,4.703700e+00,8.896000e+01,3.649307e+00,1.600000e+01

In [ ]:
ds.isnull().sum()